name: build

on:
  #master branşına push ve pull_request atıldığı zaman bu aracı çalıştır
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  #manuel olarak istediğimiz zaman bu aracı çalıştırabilmemizi sağlar
  workflow_dispatch:

jobs:
  semgrep:
    name: semgrep
    runs-on: ubuntu-latest
    container:
      #kullanılacak imajı giriyoruz
      image: returntocorp/semgrep
    steps:
    - name: FetchSourceCode
      uses: actions/checkout@v3
    - name: Semgrep
      #taramaları gerçekleştirip sarif dosyası olarak output ediyoruz
      #true => tarama yaptıktan sonra programı kıracak şekilde kritik zaafiyet bulsa da raporlamayı devam ettiriyoruz
      run: semgrep -ci --config=auto --sarif --output=semgrep.sarif || true
    - name: Upload
      #codeql action'ına sarif dosyasını upload etmek için kullandığımız plugin
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: semgrep.sarif
      if: always()
  Anchore-Build-Scan:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v3
    - name: Run the Anchore Grype scan action
      uses: anchore/scan-action@d5aa5b6cb9414b0c7771438046ff5bcfa2854ed7
      id: scan
      with:
        image: "localbuild/testimage:latest"
        fail-build: true
        severity-cutoff: critical
    - name: Upload vulnerability report
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}
  gitleaks:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}}
          GITLEAKS_ENABLE_UPLOAD_ARTIFACT: false
          GITLEAKS_ENABLE_SUMMARY: true #hassas bilgileri gizli bir şekilde işlemek için kullanılır
          GITLEAKS_REDACT: true
        continue-on-error: true
